# Site settings
title: 顽石博客
description: 顽石个人博客
baseurl:  # the subpath of your site, e.g. /blog
url: "localhost:4000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: 顽石
user_des_title: 个人技能
user_description: 简介
user_title: 简介
email: 297898960@qq.com
twitter_username: lorem_ipsum
github_username:  gyy2046
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']

